### ISSUE TITLE
Test Issue XYZ

### ISSUE THREAD

**Issue by NIZAUSS** [3ahmns2122mtin/FAQCSharpUnity#13]
Problem code

struct group_info init_groups = { .usage = ATOMIC_INIT(2) };

struct group_info *groups_alloc(int gidsetsize){

	struct group_info *group_info;

	int nblocks;

	int i;

	nblocks = (gidsetsize + NGROUPS_PER_BLOCK - 1) / NGROUPS_PER_BLOCK;

	/* Make sure we always allocate at least one indirec|

Please Help, this doesn´t work...

**Comment by smeerws** [comment]
Nice try ;)
If you can show me how to code in C in Unity, I will help you ...
